# Generated by Django 6.0.3 on 2026-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mods/'),
        ),
        migrations.AddField(
            model_name='modpack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modpacks/'),
        ),
        migrations.AddField(
            model_name='shader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shaders/'),
        ),
        migrations.AddField(
            model_name='texturepack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='texture-packs/'),
        ),
        migrations.AddField(
            model_name='world',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='worlds/'),
        ),
    ]
